# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME


font_family     Victor Mono
font_size       18.0

bell_path /home/winfield/games/bonfire/StarCraft_Sound_Pack/StarCraft_Sound_Pack/Glue/mousedown2.wav

background_opacity    0.97
# background_blur       200
# background_image       /home/winfield/images/walls/camille-couvez-H5PnIYI_1I0-unsplash.png
# background_tint       0.9

tab_bar_style         powerline

map ctrl+shift+t launch --cwd=current --type=tab
map shift+left previous_tab
map shift+right next_tab
